version: "3.7"

services:
  node-server:
    image: ghcr.io/laxamentumtech/audnexus:latest
    restart: always
    environment:
      ADP_TOKEN: ${NODE_ADP_TOKEN}
      MAX_REQUESTS: ${NODE_MAX_REQUESTS:-300}
      MONGODB_URI: ${NODE_MONGODB_URI:-mongodb://mongo:27017/audnexus}
      PRIVATE_KEY: ${NODE_PRIVATE_KEY}
      REDIS_URL: ${NODE_REDIS_URL:-redis://redis:6379}
      UPDATE_INTERVAL: ${NODE_UPDATE_INTERVAL:-30}
      UPDATE_THRESHOLD: ${NODE_UPDATE_THRESHOLD:-7}
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    networks:
      - traefik-overlay
      - internal
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-overlay"
        - "traefik.http.routers.node-server.rule=Host(`${TRAEFIK_DOMAIN}`)"
        - "traefik.http.routers.node-server.entrypoints=websecure"
        - "traefik.http.routers.redirs.entrypoints=websecure"
        - "traefik.http.services.node-server.loadbalancer.server.port=3000"
      replicas: 15

  mongo:
    image: mongo:7@sha256:42c8c713073c4382e03f9fa713f9b79d601383e412cd1eba30c55fe70c2ddacd
    restart: always
    volumes:
      - /mnt/docker/mongo/data:/data/db
    networks:
      - internal
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine@sha256:7635b0bfdd7dd8552b4b31d6541fef07b734614045b45a52fd5cc27c9dada9e2
    restart: always
    networks:
      - internal
    ports:
      - "6379:6379"

  traefik:
    image: traefik:v3.0@sha256:82ff6e5f9c4b357e928aef267f1873f2a86aa656a53054d1d16f39529a0ee9ff
    restart: always
    command:
      - "--providers.docker=true"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.http.tls=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${TRAEFIK_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - /mnt/docker/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-overlay
    deploy:
      replicas: 1

networks:
  traefik-overlay:
  internal:
