version: "3.7"

services:
  node-server:
    image: ghcr.io/laxamentumtech/audnexus:main@sha256:8c3aa18c81ce6780112b9a9bb0987a91f83e7b01f3269e458e491e28b4654970
    restart: always
    environment:
      ADP_TOKEN: ${NODE_ADP_TOKEN}
      MAX_REQUESTS: ${NODE_MAX_REQUESTS:-300}
      MONGODB_URI: ${NODE_MONGODB_URI:-mongodb://mongo:27017/audnexus}
      PRIVATE_KEY: ${NODE_PRIVATE_KEY}
      REDIS_URL: ${NODE_REDIS_URL:-redis://redis:6379}
      UPDATE_INTERVAL: ${NODE_UPDATE_INTERVAL:-30}
      UPDATE_THRESHOLD: ${NODE_UPDATE_THRESHOLD:-7}
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    networks:
      - traefik-overlay
      - internal
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-overlay"
        - "traefik.http.routers.node-server.rule=Host(`${TRAEFIK_DOMAIN}`)"
        - "traefik.http.routers.node-server.entrypoints=websecure"
        - "traefik.http.routers.redirs.entrypoints=websecure"
        - "traefik.http.services.node-server.loadbalancer.server.port=3000"
      replicas: 15

  mongo:
    image: mongo:7@sha256:d341a86584b96eb665345a8f5b35fba8695ee1d0618fd012ec4696223a3d6c62
    restart: always
    volumes:
      - /mnt/docker/mongo/data:/data/db
    networks:
      - internal
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine@sha256:343e6546f35877801de0b8580274a5e3a8e8464cabe545a2dd9f3c78df77542a
    restart: always
    networks:
      - internal
    ports:
      - "6379:6379"

  traefik:
    image: traefik:v3.0@sha256:a25aa319fe3cc8095e4b1dcd8394430103a2e324e1af321312b45c266ba3e129
    restart: always
    command:
      - "--providers.docker=true"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.http.tls=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${TRAEFIK_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - /mnt/docker/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-overlay
    deploy:
      replicas: 1

networks:
  traefik-overlay:
  internal:
