name: 'jest-coverage'
on:
  pull_request:
    branches:
      - develop
      - main
jobs:
  coverage:
    env:
      ADP_TOKEN: ${{ secrets.ADP_TOKEN }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    permissions:
      checks: write
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
        with:
          version: latest
      - uses: ArtiomTr/jest-coverage-report-action@f1a1382101d9b92b38e3df05c9ed89a834af97c8 # v2
        with:
          test-script: pnpm test
          package-manager: pnpm
