# https://github.com/pnpm/action-setup

name: Node.js CI

on:
  schedule:
    - cron: "0 13 * * 1"
  push:
    branches: [main, develop, renovate/*]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    env:
      ADP_TOKEN: ${{ secrets.ADP_TOKEN }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["lts/*", "current"]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run linter
        run: pnpm lint
      - name: Run tests
        run: pnpm test
