# https://github.com/pnpm/action-setup

name: Node.js CI

on:
  schedule:
    - cron: "0 13 * * 1"
  push:
    branches: [main, develop, renovate/*]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    env:
      ADP_TOKEN: ${{ secrets.ADP_TOKEN }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["lts/*", "current"]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run linter
        run: pnpm lint
      - name: Run tests
        run: pnpm test
